cache_selected_only: false
debug: false
defer: false
defer_state: false
deprecated_favor_state: false
fail_fast: true
favor_state: false
indirect_selection: true
log_cache_events: false
log_format: false
log_format_file: false
log_level: false
log_level_file: false
log_path: false
partial_parse: true
populate_cache: true
print: true
printer_width: false
profile: true
quiet: true
record_timing_info: true
send_anonymous_usage_stats: false
state: false
static_parser: true
target: true
use_colors: false
use_colors_file: false
use_experimental_parser: false
version: false
version_check: true
warn_error: false
warn_error_options: false
write_json: false
